#!/usr/bin/env bash
# pm/infra/cloudflare/setup_named_tunnel.sh
# 为 htexvisa.com 创建 Cloudflare Named Tunnel + DNS CNAME
#
# 前置:
#   brew install cloudflared
#   cloudflared tunnel login   # 浏览器选 htexvisa.com zone
#
# 用法:
#   bash pm/infra/cloudflare/setup_named_tunnel.sh
#   TUNNEL_NAME=my-tunnel FRONTEND_PORT=5173 BACKEND_PORT=8000 bash pm/infra/cloudflare/setup_named_tunnel.sh

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${BLUE}[cf-tunnel]${NC} $*" >&2; }
warn() { echo -e "${YELLOW}[cf-tunnel]${NC} $*" >&2; }
err()  { echo -e "${RED}[cf-tunnel]${NC} $*" >&2; }
ok()   { echo -e "${GREEN}[cf-tunnel]${NC} $*" >&2; }

DOMAIN="${DOMAIN:-htexvisa.com}"
TUNNEL_NAME="${TUNNEL_NAME:-htex-visa}"
FRONTEND_PORT="${FRONTEND_PORT:-5173}"
BACKEND_PORT="${BACKEND_PORT:-8000}"
CF_DIR="${HOME}/.cloudflared"
CONFIG_FILE="${CF_DIR}/config.yml"

if ! command -v cloudflared >/dev/null 2>&1; then
  err "cloudflared 未安装"
  echo "  brew install cloudflared"
  exit 1
fi

mkdir -p "$CF_DIR"

# ---------- 检查是否已登录 ----------
if [ ! -f "${CF_DIR}/cert.pem" ]; then
  err "未登录 Cloudflare"
  echo ""
  echo "  先运行: cloudflared tunnel login"
  echo "  浏览器里选 zone: ${DOMAIN}"
  exit 1
fi

# ---------- 创建 tunnel（已存在则跳过）----------
if cloudflared tunnel list 2>/dev/null | grep -q "${TUNNEL_NAME}"; then
  warn "Tunnel '${TUNNEL_NAME}' 已存在, 跳过创建"
  TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2 == n {print $1; exit}')
else
  log "创建 tunnel: ${TUNNEL_NAME} ..."
  CREATE_OUT=$(cloudflared tunnel create "$TUNNEL_NAME" 2>&1)
  echo "$CREATE_OUT" >&2
  TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2 == n {print $1; exit}')
fi

if [ -z "${TUNNEL_ID:-}" ]; then
  err "拿不到 tunnel ID"
  exit 1
fi
ok "Tunnel ID: ${TUNNEL_ID}"

CREDS_FILE="${CF_DIR}/${TUNNEL_ID}.json"
if [ ! -f "$CREDS_FILE" ]; then
  err "找不到 credentials: ${CREDS_FILE}"
  exit 1
fi

# ---------- 写 config.yml ----------
log "写入 ${CONFIG_FILE} ..."
cat > "$CONFIG_FILE" <<EOF
# Auto-generated by setup_named_tunnel.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
tunnel: ${TUNNEL_ID}
credentials-file: ${CREDS_FILE}

ingress:
  - hostname: api.${DOMAIN}
    service: http://localhost:${BACKEND_PORT}
    originRequest:
      connectTimeout: 30s

  - hostname: ${DOMAIN}
    service: http://localhost:${FRONTEND_PORT}

  - hostname: www.${DOMAIN}
    service: http://localhost:${FRONTEND_PORT}

  - service: http_status:404
EOF
ok "config.yml 已更新"

# ---------- DNS CNAME ----------
for HOST in "${DOMAIN}" "www.${DOMAIN}" "api.${DOMAIN}"; do
  log "DNS route: ${HOST} → tunnel ..."
  if cloudflared tunnel route dns "$TUNNEL_NAME" "$HOST" 2>&1; then
    ok "  ${HOST} OK"
  else
    warn "  ${HOST} 可能已存在或需手动添加"
  fi
done

# ---------- 更新 backend/.env 提示 ----------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
BACKEND_ENV="${PROJECT_ROOT}/backend/.env"

echo ""
echo "════════════════════════════════════════════════════════════"
ok "Tunnel 就绪: ${TUNNEL_NAME} (${TUNNEL_ID})"
echo ""
echo "  配置文件: ${CONFIG_FILE}"
echo "  域名:"
echo "    https://${DOMAIN}          → localhost:${FRONTEND_PORT}"
echo "    https://www.${DOMAIN}      → localhost:${FRONTEND_PORT}"
echo "    https://api.${DOMAIN}      → localhost:${BACKEND_PORT}"
echo ""
echo "  启动 Tunnel:"
echo "    cloudflared tunnel run ${TUNNEL_NAME}"
echo ""
echo "  启动服务后再跑 Tunnel。生产 env 建议:"
echo "    APP_FRONTEND_BASE=https://${DOMAIN}"
echo "    CORS_ALLOWED_ORIGINS=https://${DOMAIN},https://www.${DOMAIN}"
echo "    PUBLIC_BASE_URL=https://api.${DOMAIN}"
echo ""
echo "  验证: bash pm/infra/cloudflare/verify_dns.sh"
echo "════════════════════════════════════════════════════════════"
