// mapping.js — DS-160 字段映射 + 引导单生成(插件版,classic script)
// =============================================================================
// ⚠️ 自动生成 — 不要手改。请改 frontend/web/src/data/ds160FieldMap.js 后跑:
//    cd frontend/web && node scripts/build-extension-mapping.mjs
// =============================================================================
(function () {
  var VERSION = "2026.3"
  var VERIFIED_DATE = null
  var MONTHS = ["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"]

  // ---- when helpers (跟 ds160When.js 行为一致) ----
  function _get(o, p) {
    if (o == null) return undefined
    return String(p).split('.').reduce(function (a, k) { return a == null ? undefined : a[k] }, o)
  }
  function _isNonEmpty(v) {
    if (v === undefined || v === null) return false
    if (typeof v === 'string') return v.trim() !== ''
    if (typeof v === 'boolean') return true
    if (typeof v === 'number') return !Number.isNaN(v)
    if (Array.isArray(v)) return v.length > 0
    if (typeof v === 'object') return Object.keys(v).length > 0
    return true
  }
  function _boolCoerce(v) {
    if (typeof v === 'boolean') return v
    if (typeof v === 'string') {
      var s = v.trim().toLowerCase()
      if (s === 'true' || s === 'yes' || s === '1') return true
      return false
    }
    return Boolean(v)
  }
  function _looseEqual(a, b) {
    if (a === b) return true
    if (a == null && b == null) return true
    if (typeof a === 'boolean' || typeof b === 'boolean') return _boolCoerce(a) === _boolCoerce(b)
    if (typeof a === 'number' || typeof b === 'number') {
      var na = Number(a), nb = Number(b)
      if (!Number.isNaN(na) && !Number.isNaN(nb)) return na === nb
    }
    if (typeof a === 'string' && typeof b === 'string') {
      return a.trim().toLowerCase() === b.trim().toLowerCase()
    }
    return false
  }

  // ---- field map (when 编译成函数) ----
  var MAP = [
  {
    "section": "personal1",
    "officialTitle": "Personal Information 1",
    "manual": false,
    "whenSrc": null,
    "fields": [
      {
        "label": "Surnames",
        "profile": "identity.surname",
        "input": "text",
        "transform": "upper",
        "optional": false,
        "note": "护照上的姓(拼音全大写)",
        "whenSrc": null
      },
      {
        "label": "Given Names",
        "profile": "identity.givenName",
        "input": "text",
        "transform": "upper",
        "optional": false,
        "note": "护照上的名(拼音全大写)",
        "whenSrc": null
      },
      {
        "label": "Full Name in Native Alphabet",
        "profile": "identity.nativeName",
        "input": "text",
        "optional": true,
        "note": "中文/越南语/印尼语原名；确实没有则勾 \"Does Not Apply\"",
        "whenSrc": null
      },
      {
        "label": "Sex",
        "profile": "identity.sex",
        "input": "select",
        "valueMap": {
          "M": "MALE",
          "F": "FEMALE"
        },
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Marital Status",
        "profile": "identity.maritalStatus",
        "input": "select",
        "valueMap": {
          "single": "SINGLE",
          "married": "MARRIED",
          "divorced": "DIVORCED",
          "widowed": "WIDOWED",
          "separated": "SEPARATED"
        },
        "optional": false,
        "note": "SEPARATED(分居)也在选项里",
        "whenSrc": null
      },
      {
        "label": "Date of Birth",
        "profile": "identity.dob",
        "input": "date",
        "transform": "date",
        "optional": false,
        "note": "官网格式 日-月缩写-年",
        "whenSrc": null
      },
      {
        "label": "City of Birth",
        "profile": "identity.birthCity",
        "input": "text",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Country/Region of Birth",
        "profile": "identity.birthCountry",
        "input": "select",
        "valueMap": {
          "AF": "AFGHANISTAN",
          "AX": "ALAND ISLANDS",
          "AL": "ALBANIA",
          "DZ": "ALGERIA",
          "AS": "AMERICAN SAMOA",
          "AD": "ANDORRA",
          "AO": "ANGOLA",
          "AI": "ANGUILLA",
          "AQ": "ANTARCTICA",
          "AG": "ANTIGUA AND BARBUDA",
          "AR": "ARGENTINA",
          "AM": "ARMENIA",
          "AW": "ARUBA",
          "AU": "AUSTRALIA",
          "AT": "AUSTRIA",
          "AZ": "AZERBAIJAN",
          "BS": "BAHAMAS",
          "BH": "BAHRAIN",
          "BD": "BANGLADESH",
          "BB": "BARBADOS",
          "BY": "BELARUS",
          "BE": "BELGIUM",
          "BZ": "BELIZE",
          "BJ": "BENIN",
          "BM": "BERMUDA",
          "BT": "BHUTAN",
          "BO": "BOLIVIA",
          "BA": "BOSNIA AND HERZEGOVINA",
          "BW": "BOTSWANA",
          "BV": "BOUVET ISLAND",
          "BR": "BRAZIL",
          "IO": "BRITISH INDIAN OCEAN TERRITORY",
          "BN": "BRUNEI DARUSSALAM",
          "BG": "BULGARIA",
          "BF": "BURKINA FASO",
          "BI": "BURUNDI",
          "KH": "CAMBODIA",
          "CM": "CAMEROON",
          "CA": "CANADA",
          "CV": "CAPE VERDE",
          "KY": "CAYMAN ISLANDS",
          "CF": "CENTRAL AFRICAN REPUBLIC",
          "TD": "CHAD",
          "CL": "CHILE",
          "CN": "CHINA, PEOPLE'S REPUBLIC OF",
          "CN_MAINLAND": "CHINA-MAINLAND",
          "CN_HK": "CHINA, HONG KONG SAR",
          "CN_MACAU": "CHINA, MACAU SAR",
          "CN_TAIWAN": "CHINA, TAIWAN",
          "CX": "CHRISTMAS ISLAND",
          "CC": "COCOS ISLANDS",
          "CO": "COLOMBIA",
          "KM": "COMOROS",
          "CG": "CONGO",
          "CD": "CONGO, DEMOCRATIC REPUBLIC OF THE",
          "CK": "COOK ISLANDS",
          "CR": "COSTA RICA",
          "CI": "COTE D'IVOIRE",
          "HR": "CROATIA",
          "CU": "CUBA",
          "CY": "CYPRUS",
          "CZ": "CZECH REPUBLIC",
          "DK": "DENMARK",
          "DJ": "DJIBOUTI",
          "DM": "DOMINICA",
          "DO": "DOMINICAN REPUBLIC",
          "EC": "ECUADOR",
          "EG": "EGYPT",
          "SV": "EL SALVADOR",
          "GQ": "EQUATORIAL GUINEA",
          "ER": "ERITREA",
          "EE": "ESTONIA",
          "ET": "ETHIOPIA",
          "FK": "FALKLAND ISLANDS",
          "FO": "FAROE ISLANDS",
          "FJ": "FIJI",
          "FI": "FINLAND",
          "FR": "FRANCE",
          "GF": "FRENCH GUIANA",
          "PF": "FRENCH POLYNESIA",
          "TF": "FRENCH SOUTHERN TERRITORIES",
          "GA": "GABON",
          "GM": "GAMBIA",
          "GE": "GEORGIA",
          "DE": "GERMANY",
          "GH": "GHANA",
          "GI": "GIBRALTAR",
          "GR": "GREECE",
          "GL": "GREENLAND",
          "GD": "GRENADA",
          "GP": "GUADELOUPE",
          "GU": "GUAM",
          "GT": "GUATEMALA",
          "GG": "GUERNSEY",
          "GN": "GUINEA",
          "GW": "GUINEA-BISSAU",
          "GY": "GUYANA",
          "HT": "HAITI",
          "HM": "HEARD ISLAND AND MCDONALD ISLANDS",
          "VA": "HOLY SEE (VATICAN CITY STATE)",
          "HN": "HONDURAS",
          "HK": "HONG KONG",
          "HU": "HUNGARY",
          "IS": "ICELAND",
          "IN": "INDIA",
          "ID": "INDONESIA",
          "IR": "IRAN, ISLAMIC REPUBLIC OF",
          "IQ": "IRAQ",
          "IE": "IRELAND",
          "IM": "ISLE OF MAN",
          "IL": "ISRAEL",
          "IT": "ITALY",
          "JM": "JAMAICA",
          "JP": "JAPAN",
          "JE": "JERSEY",
          "JO": "JORDAN",
          "KZ": "KAZAKHSTAN",
          "KE": "KENYA",
          "KI": "KIRIBATI",
          "KP": "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
          "KR": "KOREA, REPUBLIC OF",
          "KW": "KUWAIT",
          "KG": "KYRGYZSTAN",
          "LA": "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
          "LV": "LATVIA",
          "LB": "LEBANON",
          "LS": "LESOTHO",
          "LR": "LIBERIA",
          "LY": "LIBYAN ARAB JAMAHIRIYA",
          "LI": "LIECHTENSTEIN",
          "LT": "LITHUANIA",
          "LU": "LUXEMBOURG",
          "MO": "MACAO",
          "MK": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
          "MG": "MADAGASCAR",
          "MW": "MALAWI",
          "MY": "MALAYSIA",
          "MV": "MALDIVES",
          "ML": "MALI",
          "MT": "MALTA",
          "MH": "MARSHALL ISLANDS",
          "MQ": "MARTINIQUE",
          "MR": "MAURITANIA",
          "MU": "MAURITIUS",
          "YT": "MAYOTTE",
          "MX": "MEXICO",
          "FM": "MICRONESIA, FEDERATED STATES OF",
          "MD": "MOLDOVA, REPUBLIC OF",
          "MC": "MONACO",
          "MN": "MONGOLIA",
          "ME": "MONTENEGRO",
          "MS": "MONTSERRAT",
          "MA": "MOROCCO",
          "MZ": "MOZAMBIQUE",
          "MM": "MYANMAR",
          "NA": "NAMIBIA",
          "NR": "NAURU",
          "NP": "NEPAL",
          "NL": "NETHERLANDS",
          "AN": "NETHERLANDS ANTILLES",
          "NC": "NEW CALEDONIA",
          "NZ": "NEW ZEALAND",
          "NI": "NICARAGUA",
          "NE": "NIGER",
          "NG": "NIGERIA",
          "NU": "NIUE",
          "NF": "NORFOLK ISLAND",
          "MK_NORTH": "NORTH MACEDONIA",
          "MP": "NORTHERN MARIANA ISLANDS",
          "NO": "NORWAY",
          "OM": "OMAN",
          "PK": "PAKISTAN",
          "PW": "PALAU",
          "PS": "PALESTINIAN TERRITORY, OCCUPIED",
          "PA": "PANAMA",
          "PG": "PAPUA NEW GUINEA",
          "PY": "PARAGUAY",
          "PE": "PERU",
          "PH": "PHILIPPINES",
          "PN": "PITCAIRN",
          "PL": "POLAND",
          "PT": "PORTUGAL",
          "PR": "PUERTO RICO",
          "QA": "QATAR",
          "RE": "REUNION",
          "RO": "ROMANIA",
          "RU": "RUSSIAN FEDERATION",
          "RW": "RWANDA",
          "SH": "SAINT HELENA",
          "KN": "SAINT KITTS AND NEVIS",
          "LC": "SAINT LUCIA",
          "PM": "SAINT PIERRE AND MIQUELON",
          "VC": "SAINT VINCENT AND THE GRENADINES",
          "WS": "SAMOA",
          "SM": "SAN MARINO",
          "ST": "SAO TOME AND PRINCIPE",
          "SA": "SAUDI ARABIA",
          "SN": "SENEGAL",
          "RS": "SERBIA",
          "SC": "SEYCHELLES",
          "SL": "SIERRA LEONE",
          "SG": "SINGAPORE",
          "SK": "SLOVAKIA",
          "SI": "SLOVENIA",
          "SB": "SOLOMON ISLANDS",
          "SO": "SOMALIA",
          "ZA": "SOUTH AFRICA",
          "GS": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
          "ES": "SPAIN",
          "LK": "SRI LANKA",
          "SD": "SUDAN",
          "SR": "SURINAME",
          "SJ": "SVALBARD AND JAN MAYEN",
          "SZ": "SWAZILAND",
          "SE": "SWEDEN",
          "CH": "SWITZERLAND",
          "SY": "SYRIAN ARAB REPUBLIC",
          "TW": "TAIWAN",
          "TJ": "TAJIKISTAN",
          "TZ": "TANZANIA, UNITED REPUBLIC OF",
          "TH": "THAILAND",
          "TL": "TIMOR-LESTE",
          "TG": "TOGO",
          "TK": "TOKELAU",
          "TO": "TONGA",
          "TT": "TRINIDAD AND TOBAGO",
          "TN": "TUNISIA",
          "TR": "TURKEY",
          "TM": "TURKMENISTAN",
          "TC": "TURKS AND CAICOS ISLANDS",
          "TV": "TUVALU",
          "UG": "UGANDA",
          "UA": "UKRAINE",
          "AE": "UNITED ARAB EMIRATES",
          "GB": "UNITED KINGDOM",
          "US": "UNITED STATES",
          "UM": "UNITED STATES MINOR OUTLYING ISLANDS",
          "UY": "URUGUAY",
          "UZ": "UZBEKISTAN",
          "VU": "VANUATU",
          "VE": "VENEZUELA",
          "VN": "VIETNAM",
          "VG": "VIRGIN ISLANDS, BRITISH",
          "VI": "VIRGIN ISLANDS, U.S.",
          "WF": "WALLIS AND FUTUNA",
          "EH": "WESTERN SAHARA",
          "YE": "YEMEN",
          "ZM": "ZAMBIA",
          "ZW": "ZIMBABWE",
          "XX": "STATELESS"
        },
        "optional": false,
        "note": "ISO-2 代码 (VN/ID/CN/...) → DS-160 官方下拉枚举",
        "whenSrc": null
      }
    ]
  },
  {
    "section": "personal2",
    "officialTitle": "Personal Information 2",
    "manual": false,
    "whenSrc": null,
    "fields": [
      {
        "label": "Country/Region of Origin (Nationality)",
        "profile": "identity.nationality",
        "input": "select",
        "valueMap": {
          "AF": "AFGHANISTAN",
          "AX": "ALAND ISLANDS",
          "AL": "ALBANIA",
          "DZ": "ALGERIA",
          "AS": "AMERICAN SAMOA",
          "AD": "ANDORRA",
          "AO": "ANGOLA",
          "AI": "ANGUILLA",
          "AQ": "ANTARCTICA",
          "AG": "ANTIGUA AND BARBUDA",
          "AR": "ARGENTINA",
          "AM": "ARMENIA",
          "AW": "ARUBA",
          "AU": "AUSTRALIA",
          "AT": "AUSTRIA",
          "AZ": "AZERBAIJAN",
          "BS": "BAHAMAS",
          "BH": "BAHRAIN",
          "BD": "BANGLADESH",
          "BB": "BARBADOS",
          "BY": "BELARUS",
          "BE": "BELGIUM",
          "BZ": "BELIZE",
          "BJ": "BENIN",
          "BM": "BERMUDA",
          "BT": "BHUTAN",
          "BO": "BOLIVIA",
          "BA": "BOSNIA AND HERZEGOVINA",
          "BW": "BOTSWANA",
          "BV": "BOUVET ISLAND",
          "BR": "BRAZIL",
          "IO": "BRITISH INDIAN OCEAN TERRITORY",
          "BN": "BRUNEI DARUSSALAM",
          "BG": "BULGARIA",
          "BF": "BURKINA FASO",
          "BI": "BURUNDI",
          "KH": "CAMBODIA",
          "CM": "CAMEROON",
          "CA": "CANADA",
          "CV": "CAPE VERDE",
          "KY": "CAYMAN ISLANDS",
          "CF": "CENTRAL AFRICAN REPUBLIC",
          "TD": "CHAD",
          "CL": "CHILE",
          "CN": "CHINA, PEOPLE'S REPUBLIC OF",
          "CN_MAINLAND": "CHINA-MAINLAND",
          "CN_HK": "CHINA, HONG KONG SAR",
          "CN_MACAU": "CHINA, MACAU SAR",
          "CN_TAIWAN": "CHINA, TAIWAN",
          "CX": "CHRISTMAS ISLAND",
          "CC": "COCOS ISLANDS",
          "CO": "COLOMBIA",
          "KM": "COMOROS",
          "CG": "CONGO",
          "CD": "CONGO, DEMOCRATIC REPUBLIC OF THE",
          "CK": "COOK ISLANDS",
          "CR": "COSTA RICA",
          "CI": "COTE D'IVOIRE",
          "HR": "CROATIA",
          "CU": "CUBA",
          "CY": "CYPRUS",
          "CZ": "CZECH REPUBLIC",
          "DK": "DENMARK",
          "DJ": "DJIBOUTI",
          "DM": "DOMINICA",
          "DO": "DOMINICAN REPUBLIC",
          "EC": "ECUADOR",
          "EG": "EGYPT",
          "SV": "EL SALVADOR",
          "GQ": "EQUATORIAL GUINEA",
          "ER": "ERITREA",
          "EE": "ESTONIA",
          "ET": "ETHIOPIA",
          "FK": "FALKLAND ISLANDS",
          "FO": "FAROE ISLANDS",
          "FJ": "FIJI",
          "FI": "FINLAND",
          "FR": "FRANCE",
          "GF": "FRENCH GUIANA",
          "PF": "FRENCH POLYNESIA",
          "TF": "FRENCH SOUTHERN TERRITORIES",
          "GA": "GABON",
          "GM": "GAMBIA",
          "GE": "GEORGIA",
          "DE": "GERMANY",
          "GH": "GHANA",
          "GI": "GIBRALTAR",
          "GR": "GREECE",
          "GL": "GREENLAND",
          "GD": "GRENADA",
          "GP": "GUADELOUPE",
          "GU": "GUAM",
          "GT": "GUATEMALA",
          "GG": "GUERNSEY",
          "GN": "GUINEA",
          "GW": "GUINEA-BISSAU",
          "GY": "GUYANA",
          "HT": "HAITI",
          "HM": "HEARD ISLAND AND MCDONALD ISLANDS",
          "VA": "HOLY SEE (VATICAN CITY STATE)",
          "HN": "HONDURAS",
          "HK": "HONG KONG",
          "HU": "HUNGARY",
          "IS": "ICELAND",
          "IN": "INDIA",
          "ID": "INDONESIA",
          "IR": "IRAN, ISLAMIC REPUBLIC OF",
          "IQ": "IRAQ",
          "IE": "IRELAND",
          "IM": "ISLE OF MAN",
          "IL": "ISRAEL",
          "IT": "ITALY",
          "JM": "JAMAICA",
          "JP": "JAPAN",
          "JE": "JERSEY",
          "JO": "JORDAN",
          "KZ": "KAZAKHSTAN",
          "KE": "KENYA",
          "KI": "KIRIBATI",
          "KP": "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
          "KR": "KOREA, REPUBLIC OF",
          "KW": "KUWAIT",
          "KG": "KYRGYZSTAN",
          "LA": "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
          "LV": "LATVIA",
          "LB": "LEBANON",
          "LS": "LESOTHO",
          "LR": "LIBERIA",
          "LY": "LIBYAN ARAB JAMAHIRIYA",
          "LI": "LIECHTENSTEIN",
          "LT": "LITHUANIA",
          "LU": "LUXEMBOURG",
          "MO": "MACAO",
          "MK": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
          "MG": "MADAGASCAR",
          "MW": "MALAWI",
          "MY": "MALAYSIA",
          "MV": "MALDIVES",
          "ML": "MALI",
          "MT": "MALTA",
          "MH": "MARSHALL ISLANDS",
          "MQ": "MARTINIQUE",
          "MR": "MAURITANIA",
          "MU": "MAURITIUS",
          "YT": "MAYOTTE",
          "MX": "MEXICO",
          "FM": "MICRONESIA, FEDERATED STATES OF",
          "MD": "MOLDOVA, REPUBLIC OF",
          "MC": "MONACO",
          "MN": "MONGOLIA",
          "ME": "MONTENEGRO",
          "MS": "MONTSERRAT",
          "MA": "MOROCCO",
          "MZ": "MOZAMBIQUE",
          "MM": "MYANMAR",
          "NA": "NAMIBIA",
          "NR": "NAURU",
          "NP": "NEPAL",
          "NL": "NETHERLANDS",
          "AN": "NETHERLANDS ANTILLES",
          "NC": "NEW CALEDONIA",
          "NZ": "NEW ZEALAND",
          "NI": "NICARAGUA",
          "NE": "NIGER",
          "NG": "NIGERIA",
          "NU": "NIUE",
          "NF": "NORFOLK ISLAND",
          "MK_NORTH": "NORTH MACEDONIA",
          "MP": "NORTHERN MARIANA ISLANDS",
          "NO": "NORWAY",
          "OM": "OMAN",
          "PK": "PAKISTAN",
          "PW": "PALAU",
          "PS": "PALESTINIAN TERRITORY, OCCUPIED",
          "PA": "PANAMA",
          "PG": "PAPUA NEW GUINEA",
          "PY": "PARAGUAY",
          "PE": "PERU",
          "PH": "PHILIPPINES",
          "PN": "PITCAIRN",
          "PL": "POLAND",
          "PT": "PORTUGAL",
          "PR": "PUERTO RICO",
          "QA": "QATAR",
          "RE": "REUNION",
          "RO": "ROMANIA",
          "RU": "RUSSIAN FEDERATION",
          "RW": "RWANDA",
          "SH": "SAINT HELENA",
          "KN": "SAINT KITTS AND NEVIS",
          "LC": "SAINT LUCIA",
          "PM": "SAINT PIERRE AND MIQUELON",
          "VC": "SAINT VINCENT AND THE GRENADINES",
          "WS": "SAMOA",
          "SM": "SAN MARINO",
          "ST": "SAO TOME AND PRINCIPE",
          "SA": "SAUDI ARABIA",
          "SN": "SENEGAL",
          "RS": "SERBIA",
          "SC": "SEYCHELLES",
          "SL": "SIERRA LEONE",
          "SG": "SINGAPORE",
          "SK": "SLOVAKIA",
          "SI": "SLOVENIA",
          "SB": "SOLOMON ISLANDS",
          "SO": "SOMALIA",
          "ZA": "SOUTH AFRICA",
          "GS": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
          "ES": "SPAIN",
          "LK": "SRI LANKA",
          "SD": "SUDAN",
          "SR": "SURINAME",
          "SJ": "SVALBARD AND JAN MAYEN",
          "SZ": "SWAZILAND",
          "SE": "SWEDEN",
          "CH": "SWITZERLAND",
          "SY": "SYRIAN ARAB REPUBLIC",
          "TW": "TAIWAN",
          "TJ": "TAJIKISTAN",
          "TZ": "TANZANIA, UNITED REPUBLIC OF",
          "TH": "THAILAND",
          "TL": "TIMOR-LESTE",
          "TG": "TOGO",
          "TK": "TOKELAU",
          "TO": "TONGA",
          "TT": "TRINIDAD AND TOBAGO",
          "TN": "TUNISIA",
          "TR": "TURKEY",
          "TM": "TURKMENISTAN",
          "TC": "TURKS AND CAICOS ISLANDS",
          "TV": "TUVALU",
          "UG": "UGANDA",
          "UA": "UKRAINE",
          "AE": "UNITED ARAB EMIRATES",
          "GB": "UNITED KINGDOM",
          "US": "UNITED STATES",
          "UM": "UNITED STATES MINOR OUTLYING ISLANDS",
          "UY": "URUGUAY",
          "UZ": "UZBEKISTAN",
          "VU": "VANUATU",
          "VE": "VENEZUELA",
          "VN": "VIETNAM",
          "VG": "VIRGIN ISLANDS, BRITISH",
          "VI": "VIRGIN ISLANDS, U.S.",
          "WF": "WALLIS AND FUTUNA",
          "EH": "WESTERN SAHARA",
          "YE": "YEMEN",
          "ZM": "ZAMBIA",
          "ZW": "ZIMBABWE",
          "XX": "STATELESS"
        },
        "optional": false,
        "note": "ISO-2 代码 → DS-160 官方下拉枚举",
        "whenSrc": null
      },
      {
        "label": "Do you hold or have you held any nationality other than the one indicated above?",
        "profile": "identity.hasOtherNationality",
        "input": "radio",
        "valueMap": {
          "true": "YES",
          "false": "NO"
        },
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "National Identification Number",
        "profile": "identity.nationalId",
        "input": "text",
        "optional": true,
        "note": "身份证号/公民号；没有则勾 \"Does Not Apply\"",
        "whenSrc": null
      },
      {
        "label": "U.S. Social Security Number",
        "profile": "identity.usSsn",
        "input": "text",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "U.S. Taxpayer ID Number",
        "profile": "identity.usTaxId",
        "input": "text",
        "optional": true,
        "whenSrc": null
      }
    ]
  },
  {
    "section": "address_phone",
    "officialTitle": "Address and Phone",
    "manual": false,
    "whenSrc": null,
    "fields": [
      {
        "label": "Home Address — Street Address",
        "profile": "contact.street",
        "input": "text",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Home Address — City",
        "profile": "contact.city",
        "input": "text",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Home Address — State/Province",
        "profile": "contact.state",
        "input": "text",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Home Address — Postal Zone/ZIP Code",
        "profile": "contact.postalCode",
        "input": "text",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Home Address — Country/Region",
        "profile": "contact.country",
        "input": "select",
        "valueMap": {
          "AF": "AFGHANISTAN",
          "AX": "ALAND ISLANDS",
          "AL": "ALBANIA",
          "DZ": "ALGERIA",
          "AS": "AMERICAN SAMOA",
          "AD": "ANDORRA",
          "AO": "ANGOLA",
          "AI": "ANGUILLA",
          "AQ": "ANTARCTICA",
          "AG": "ANTIGUA AND BARBUDA",
          "AR": "ARGENTINA",
          "AM": "ARMENIA",
          "AW": "ARUBA",
          "AU": "AUSTRALIA",
          "AT": "AUSTRIA",
          "AZ": "AZERBAIJAN",
          "BS": "BAHAMAS",
          "BH": "BAHRAIN",
          "BD": "BANGLADESH",
          "BB": "BARBADOS",
          "BY": "BELARUS",
          "BE": "BELGIUM",
          "BZ": "BELIZE",
          "BJ": "BENIN",
          "BM": "BERMUDA",
          "BT": "BHUTAN",
          "BO": "BOLIVIA",
          "BA": "BOSNIA AND HERZEGOVINA",
          "BW": "BOTSWANA",
          "BV": "BOUVET ISLAND",
          "BR": "BRAZIL",
          "IO": "BRITISH INDIAN OCEAN TERRITORY",
          "BN": "BRUNEI DARUSSALAM",
          "BG": "BULGARIA",
          "BF": "BURKINA FASO",
          "BI": "BURUNDI",
          "KH": "CAMBODIA",
          "CM": "CAMEROON",
          "CA": "CANADA",
          "CV": "CAPE VERDE",
          "KY": "CAYMAN ISLANDS",
          "CF": "CENTRAL AFRICAN REPUBLIC",
          "TD": "CHAD",
          "CL": "CHILE",
          "CN": "CHINA, PEOPLE'S REPUBLIC OF",
          "CN_MAINLAND": "CHINA-MAINLAND",
          "CN_HK": "CHINA, HONG KONG SAR",
          "CN_MACAU": "CHINA, MACAU SAR",
          "CN_TAIWAN": "CHINA, TAIWAN",
          "CX": "CHRISTMAS ISLAND",
          "CC": "COCOS ISLANDS",
          "CO": "COLOMBIA",
          "KM": "COMOROS",
          "CG": "CONGO",
          "CD": "CONGO, DEMOCRATIC REPUBLIC OF THE",
          "CK": "COOK ISLANDS",
          "CR": "COSTA RICA",
          "CI": "COTE D'IVOIRE",
          "HR": "CROATIA",
          "CU": "CUBA",
          "CY": "CYPRUS",
          "CZ": "CZECH REPUBLIC",
          "DK": "DENMARK",
          "DJ": "DJIBOUTI",
          "DM": "DOMINICA",
          "DO": "DOMINICAN REPUBLIC",
          "EC": "ECUADOR",
          "EG": "EGYPT",
          "SV": "EL SALVADOR",
          "GQ": "EQUATORIAL GUINEA",
          "ER": "ERITREA",
          "EE": "ESTONIA",
          "ET": "ETHIOPIA",
          "FK": "FALKLAND ISLANDS",
          "FO": "FAROE ISLANDS",
          "FJ": "FIJI",
          "FI": "FINLAND",
          "FR": "FRANCE",
          "GF": "FRENCH GUIANA",
          "PF": "FRENCH POLYNESIA",
          "TF": "FRENCH SOUTHERN TERRITORIES",
          "GA": "GABON",
          "GM": "GAMBIA",
          "GE": "GEORGIA",
          "DE": "GERMANY",
          "GH": "GHANA",
          "GI": "GIBRALTAR",
          "GR": "GREECE",
          "GL": "GREENLAND",
          "GD": "GRENADA",
          "GP": "GUADELOUPE",
          "GU": "GUAM",
          "GT": "GUATEMALA",
          "GG": "GUERNSEY",
          "GN": "GUINEA",
          "GW": "GUINEA-BISSAU",
          "GY": "GUYANA",
          "HT": "HAITI",
          "HM": "HEARD ISLAND AND MCDONALD ISLANDS",
          "VA": "HOLY SEE (VATICAN CITY STATE)",
          "HN": "HONDURAS",
          "HK": "HONG KONG",
          "HU": "HUNGARY",
          "IS": "ICELAND",
          "IN": "INDIA",
          "ID": "INDONESIA",
          "IR": "IRAN, ISLAMIC REPUBLIC OF",
          "IQ": "IRAQ",
          "IE": "IRELAND",
          "IM": "ISLE OF MAN",
          "IL": "ISRAEL",
          "IT": "ITALY",
          "JM": "JAMAICA",
          "JP": "JAPAN",
          "JE": "JERSEY",
          "JO": "JORDAN",
          "KZ": "KAZAKHSTAN",
          "KE": "KENYA",
          "KI": "KIRIBATI",
          "KP": "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
          "KR": "KOREA, REPUBLIC OF",
          "KW": "KUWAIT",
          "KG": "KYRGYZSTAN",
          "LA": "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
          "LV": "LATVIA",
          "LB": "LEBANON",
          "LS": "LESOTHO",
          "LR": "LIBERIA",
          "LY": "LIBYAN ARAB JAMAHIRIYA",
          "LI": "LIECHTENSTEIN",
          "LT": "LITHUANIA",
          "LU": "LUXEMBOURG",
          "MO": "MACAO",
          "MK": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
          "MG": "MADAGASCAR",
          "MW": "MALAWI",
          "MY": "MALAYSIA",
          "MV": "MALDIVES",
          "ML": "MALI",
          "MT": "MALTA",
          "MH": "MARSHALL ISLANDS",
          "MQ": "MARTINIQUE",
          "MR": "MAURITANIA",
          "MU": "MAURITIUS",
          "YT": "MAYOTTE",
          "MX": "MEXICO",
          "FM": "MICRONESIA, FEDERATED STATES OF",
          "MD": "MOLDOVA, REPUBLIC OF",
          "MC": "MONACO",
          "MN": "MONGOLIA",
          "ME": "MONTENEGRO",
          "MS": "MONTSERRAT",
          "MA": "MOROCCO",
          "MZ": "MOZAMBIQUE",
          "MM": "MYANMAR",
          "NA": "NAMIBIA",
          "NR": "NAURU",
          "NP": "NEPAL",
          "NL": "NETHERLANDS",
          "AN": "NETHERLANDS ANTILLES",
          "NC": "NEW CALEDONIA",
          "NZ": "NEW ZEALAND",
          "NI": "NICARAGUA",
          "NE": "NIGER",
          "NG": "NIGERIA",
          "NU": "NIUE",
          "NF": "NORFOLK ISLAND",
          "MK_NORTH": "NORTH MACEDONIA",
          "MP": "NORTHERN MARIANA ISLANDS",
          "NO": "NORWAY",
          "OM": "OMAN",
          "PK": "PAKISTAN",
          "PW": "PALAU",
          "PS": "PALESTINIAN TERRITORY, OCCUPIED",
          "PA": "PANAMA",
          "PG": "PAPUA NEW GUINEA",
          "PY": "PARAGUAY",
          "PE": "PERU",
          "PH": "PHILIPPINES",
          "PN": "PITCAIRN",
          "PL": "POLAND",
          "PT": "PORTUGAL",
          "PR": "PUERTO RICO",
          "QA": "QATAR",
          "RE": "REUNION",
          "RO": "ROMANIA",
          "RU": "RUSSIAN FEDERATION",
          "RW": "RWANDA",
          "SH": "SAINT HELENA",
          "KN": "SAINT KITTS AND NEVIS",
          "LC": "SAINT LUCIA",
          "PM": "SAINT PIERRE AND MIQUELON",
          "VC": "SAINT VINCENT AND THE GRENADINES",
          "WS": "SAMOA",
          "SM": "SAN MARINO",
          "ST": "SAO TOME AND PRINCIPE",
          "SA": "SAUDI ARABIA",
          "SN": "SENEGAL",
          "RS": "SERBIA",
          "SC": "SEYCHELLES",
          "SL": "SIERRA LEONE",
          "SG": "SINGAPORE",
          "SK": "SLOVAKIA",
          "SI": "SLOVENIA",
          "SB": "SOLOMON ISLANDS",
          "SO": "SOMALIA",
          "ZA": "SOUTH AFRICA",
          "GS": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
          "ES": "SPAIN",
          "LK": "SRI LANKA",
          "SD": "SUDAN",
          "SR": "SURINAME",
          "SJ": "SVALBARD AND JAN MAYEN",
          "SZ": "SWAZILAND",
          "SE": "SWEDEN",
          "CH": "SWITZERLAND",
          "SY": "SYRIAN ARAB REPUBLIC",
          "TW": "TAIWAN",
          "TJ": "TAJIKISTAN",
          "TZ": "TANZANIA, UNITED REPUBLIC OF",
          "TH": "THAILAND",
          "TL": "TIMOR-LESTE",
          "TG": "TOGO",
          "TK": "TOKELAU",
          "TO": "TONGA",
          "TT": "TRINIDAD AND TOBAGO",
          "TN": "TUNISIA",
          "TR": "TURKEY",
          "TM": "TURKMENISTAN",
          "TC": "TURKS AND CAICOS ISLANDS",
          "TV": "TUVALU",
          "UG": "UGANDA",
          "UA": "UKRAINE",
          "AE": "UNITED ARAB EMIRATES",
          "GB": "UNITED KINGDOM",
          "US": "UNITED STATES",
          "UM": "UNITED STATES MINOR OUTLYING ISLANDS",
          "UY": "URUGUAY",
          "UZ": "UZBEKISTAN",
          "VU": "VANUATU",
          "VE": "VENEZUELA",
          "VN": "VIETNAM",
          "VG": "VIRGIN ISLANDS, BRITISH",
          "VI": "VIRGIN ISLANDS, U.S.",
          "WF": "WALLIS AND FUTUNA",
          "EH": "WESTERN SAHARA",
          "YE": "YEMEN",
          "ZM": "ZAMBIA",
          "ZW": "ZIMBABWE",
          "XX": "STATELESS"
        },
        "optional": false,
        "note": "ISO-2 代码 → DS-160 官方下拉枚举",
        "whenSrc": null
      },
      {
        "label": "Primary Phone Number",
        "profile": "contact.phone",
        "input": "text",
        "optional": false,
        "note": "带国家码，如 +84... +62... +86...",
        "whenSrc": null
      },
      {
        "label": "Email Address",
        "profile": "contact.email",
        "input": "text",
        "optional": false,
        "whenSrc": null
      }
    ]
  },
  {
    "section": "passport",
    "officialTitle": "Passport",
    "manual": false,
    "whenSrc": null,
    "fields": [
      {
        "label": "Passport/Travel Document Type",
        "profile": "passport.type",
        "input": "select",
        "valueMap": {
          "regular": "REGULAR",
          "official": "OFFICIAL",
          "diplomatic": "DIPLOMATIC",
          "service": "SERVICE",
          "other": "OTHER"
        },
        "optional": false,
        "note": "普通因私护照选 REGULAR",
        "whenSrc": null
      },
      {
        "label": "Passport/Travel Document Number",
        "profile": "passport.number",
        "input": "text",
        "transform": "upper",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Passport Book Number",
        "profile": "passport.bookNumber",
        "input": "text",
        "optional": true,
        "note": "多数护照没有此号 → 勾 \"Does Not Apply\"",
        "whenSrc": null
      },
      {
        "label": "Country/Authority that Issued Passport",
        "profile": "passport.issueCountry",
        "input": "select",
        "valueMap": {
          "AF": "AFGHANISTAN",
          "AX": "ALAND ISLANDS",
          "AL": "ALBANIA",
          "DZ": "ALGERIA",
          "AS": "AMERICAN SAMOA",
          "AD": "ANDORRA",
          "AO": "ANGOLA",
          "AI": "ANGUILLA",
          "AQ": "ANTARCTICA",
          "AG": "ANTIGUA AND BARBUDA",
          "AR": "ARGENTINA",
          "AM": "ARMENIA",
          "AW": "ARUBA",
          "AU": "AUSTRALIA",
          "AT": "AUSTRIA",
          "AZ": "AZERBAIJAN",
          "BS": "BAHAMAS",
          "BH": "BAHRAIN",
          "BD": "BANGLADESH",
          "BB": "BARBADOS",
          "BY": "BELARUS",
          "BE": "BELGIUM",
          "BZ": "BELIZE",
          "BJ": "BENIN",
          "BM": "BERMUDA",
          "BT": "BHUTAN",
          "BO": "BOLIVIA",
          "BA": "BOSNIA AND HERZEGOVINA",
          "BW": "BOTSWANA",
          "BV": "BOUVET ISLAND",
          "BR": "BRAZIL",
          "IO": "BRITISH INDIAN OCEAN TERRITORY",
          "BN": "BRUNEI DARUSSALAM",
          "BG": "BULGARIA",
          "BF": "BURKINA FASO",
          "BI": "BURUNDI",
          "KH": "CAMBODIA",
          "CM": "CAMEROON",
          "CA": "CANADA",
          "CV": "CAPE VERDE",
          "KY": "CAYMAN ISLANDS",
          "CF": "CENTRAL AFRICAN REPUBLIC",
          "TD": "CHAD",
          "CL": "CHILE",
          "CN": "CHINA, PEOPLE'S REPUBLIC OF",
          "CN_MAINLAND": "CHINA-MAINLAND",
          "CN_HK": "CHINA, HONG KONG SAR",
          "CN_MACAU": "CHINA, MACAU SAR",
          "CN_TAIWAN": "CHINA, TAIWAN",
          "CX": "CHRISTMAS ISLAND",
          "CC": "COCOS ISLANDS",
          "CO": "COLOMBIA",
          "KM": "COMOROS",
          "CG": "CONGO",
          "CD": "CONGO, DEMOCRATIC REPUBLIC OF THE",
          "CK": "COOK ISLANDS",
          "CR": "COSTA RICA",
          "CI": "COTE D'IVOIRE",
          "HR": "CROATIA",
          "CU": "CUBA",
          "CY": "CYPRUS",
          "CZ": "CZECH REPUBLIC",
          "DK": "DENMARK",
          "DJ": "DJIBOUTI",
          "DM": "DOMINICA",
          "DO": "DOMINICAN REPUBLIC",
          "EC": "ECUADOR",
          "EG": "EGYPT",
          "SV": "EL SALVADOR",
          "GQ": "EQUATORIAL GUINEA",
          "ER": "ERITREA",
          "EE": "ESTONIA",
          "ET": "ETHIOPIA",
          "FK": "FALKLAND ISLANDS",
          "FO": "FAROE ISLANDS",
          "FJ": "FIJI",
          "FI": "FINLAND",
          "FR": "FRANCE",
          "GF": "FRENCH GUIANA",
          "PF": "FRENCH POLYNESIA",
          "TF": "FRENCH SOUTHERN TERRITORIES",
          "GA": "GABON",
          "GM": "GAMBIA",
          "GE": "GEORGIA",
          "DE": "GERMANY",
          "GH": "GHANA",
          "GI": "GIBRALTAR",
          "GR": "GREECE",
          "GL": "GREENLAND",
          "GD": "GRENADA",
          "GP": "GUADELOUPE",
          "GU": "GUAM",
          "GT": "GUATEMALA",
          "GG": "GUERNSEY",
          "GN": "GUINEA",
          "GW": "GUINEA-BISSAU",
          "GY": "GUYANA",
          "HT": "HAITI",
          "HM": "HEARD ISLAND AND MCDONALD ISLANDS",
          "VA": "HOLY SEE (VATICAN CITY STATE)",
          "HN": "HONDURAS",
          "HK": "HONG KONG",
          "HU": "HUNGARY",
          "IS": "ICELAND",
          "IN": "INDIA",
          "ID": "INDONESIA",
          "IR": "IRAN, ISLAMIC REPUBLIC OF",
          "IQ": "IRAQ",
          "IE": "IRELAND",
          "IM": "ISLE OF MAN",
          "IL": "ISRAEL",
          "IT": "ITALY",
          "JM": "JAMAICA",
          "JP": "JAPAN",
          "JE": "JERSEY",
          "JO": "JORDAN",
          "KZ": "KAZAKHSTAN",
          "KE": "KENYA",
          "KI": "KIRIBATI",
          "KP": "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
          "KR": "KOREA, REPUBLIC OF",
          "KW": "KUWAIT",
          "KG": "KYRGYZSTAN",
          "LA": "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
          "LV": "LATVIA",
          "LB": "LEBANON",
          "LS": "LESOTHO",
          "LR": "LIBERIA",
          "LY": "LIBYAN ARAB JAMAHIRIYA",
          "LI": "LIECHTENSTEIN",
          "LT": "LITHUANIA",
          "LU": "LUXEMBOURG",
          "MO": "MACAO",
          "MK": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
          "MG": "MADAGASCAR",
          "MW": "MALAWI",
          "MY": "MALAYSIA",
          "MV": "MALDIVES",
          "ML": "MALI",
          "MT": "MALTA",
          "MH": "MARSHALL ISLANDS",
          "MQ": "MARTINIQUE",
          "MR": "MAURITANIA",
          "MU": "MAURITIUS",
          "YT": "MAYOTTE",
          "MX": "MEXICO",
          "FM": "MICRONESIA, FEDERATED STATES OF",
          "MD": "MOLDOVA, REPUBLIC OF",
          "MC": "MONACO",
          "MN": "MONGOLIA",
          "ME": "MONTENEGRO",
          "MS": "MONTSERRAT",
          "MA": "MOROCCO",
          "MZ": "MOZAMBIQUE",
          "MM": "MYANMAR",
          "NA": "NAMIBIA",
          "NR": "NAURU",
          "NP": "NEPAL",
          "NL": "NETHERLANDS",
          "AN": "NETHERLANDS ANTILLES",
          "NC": "NEW CALEDONIA",
          "NZ": "NEW ZEALAND",
          "NI": "NICARAGUA",
          "NE": "NIGER",
          "NG": "NIGERIA",
          "NU": "NIUE",
          "NF": "NORFOLK ISLAND",
          "MK_NORTH": "NORTH MACEDONIA",
          "MP": "NORTHERN MARIANA ISLANDS",
          "NO": "NORWAY",
          "OM": "OMAN",
          "PK": "PAKISTAN",
          "PW": "PALAU",
          "PS": "PALESTINIAN TERRITORY, OCCUPIED",
          "PA": "PANAMA",
          "PG": "PAPUA NEW GUINEA",
          "PY": "PARAGUAY",
          "PE": "PERU",
          "PH": "PHILIPPINES",
          "PN": "PITCAIRN",
          "PL": "POLAND",
          "PT": "PORTUGAL",
          "PR": "PUERTO RICO",
          "QA": "QATAR",
          "RE": "REUNION",
          "RO": "ROMANIA",
          "RU": "RUSSIAN FEDERATION",
          "RW": "RWANDA",
          "SH": "SAINT HELENA",
          "KN": "SAINT KITTS AND NEVIS",
          "LC": "SAINT LUCIA",
          "PM": "SAINT PIERRE AND MIQUELON",
          "VC": "SAINT VINCENT AND THE GRENADINES",
          "WS": "SAMOA",
          "SM": "SAN MARINO",
          "ST": "SAO TOME AND PRINCIPE",
          "SA": "SAUDI ARABIA",
          "SN": "SENEGAL",
          "RS": "SERBIA",
          "SC": "SEYCHELLES",
          "SL": "SIERRA LEONE",
          "SG": "SINGAPORE",
          "SK": "SLOVAKIA",
          "SI": "SLOVENIA",
          "SB": "SOLOMON ISLANDS",
          "SO": "SOMALIA",
          "ZA": "SOUTH AFRICA",
          "GS": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
          "ES": "SPAIN",
          "LK": "SRI LANKA",
          "SD": "SUDAN",
          "SR": "SURINAME",
          "SJ": "SVALBARD AND JAN MAYEN",
          "SZ": "SWAZILAND",
          "SE": "SWEDEN",
          "CH": "SWITZERLAND",
          "SY": "SYRIAN ARAB REPUBLIC",
          "TW": "TAIWAN",
          "TJ": "TAJIKISTAN",
          "TZ": "TANZANIA, UNITED REPUBLIC OF",
          "TH": "THAILAND",
          "TL": "TIMOR-LESTE",
          "TG": "TOGO",
          "TK": "TOKELAU",
          "TO": "TONGA",
          "TT": "TRINIDAD AND TOBAGO",
          "TN": "TUNISIA",
          "TR": "TURKEY",
          "TM": "TURKMENISTAN",
          "TC": "TURKS AND CAICOS ISLANDS",
          "TV": "TUVALU",
          "UG": "UGANDA",
          "UA": "UKRAINE",
          "AE": "UNITED ARAB EMIRATES",
          "GB": "UNITED KINGDOM",
          "US": "UNITED STATES",
          "UM": "UNITED STATES MINOR OUTLYING ISLANDS",
          "UY": "URUGUAY",
          "UZ": "UZBEKISTAN",
          "VU": "VANUATU",
          "VE": "VENEZUELA",
          "VN": "VIETNAM",
          "VG": "VIRGIN ISLANDS, BRITISH",
          "VI": "VIRGIN ISLANDS, U.S.",
          "WF": "WALLIS AND FUTUNA",
          "EH": "WESTERN SAHARA",
          "YE": "YEMEN",
          "ZM": "ZAMBIA",
          "ZW": "ZIMBABWE",
          "XX": "STATELESS"
        },
        "optional": false,
        "note": "ISO-2 代码 → DS-160 官方下拉枚举",
        "whenSrc": null
      },
      {
        "label": "City where Issued",
        "profile": "passport.issueCity",
        "input": "text",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Issuance Date",
        "profile": "passport.issueDate",
        "input": "date",
        "transform": "date",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Expiration Date",
        "profile": "passport.expiry",
        "input": "date",
        "transform": "date",
        "optional": false,
        "note": "需距行程 ≥6 个月",
        "whenSrc": null
      }
    ]
  },
  {
    "section": "travel",
    "officialTitle": "Travel",
    "manual": false,
    "whenSrc": null,
    "fields": [
      {
        "label": "Purpose of Trip to the U.S.",
        "profile": "travel.purpose",
        "input": "select",
        "valueMap": {
          "tourism": "TEMP. BUSINESS PLEASURE VISITOR (B)",
          "business": "TEMP. BUSINESS PLEASURE VISITOR (B)",
          "transit": "TRANSIT (C)",
          "crew": "CREW MEMBER (D)",
          "student": "STUDENT (F)",
          "work": "TEMPORARY WORKER (H)",
          "exchange": "EXCHANGE VISITOR (J)",
          "fiance": "FIANCÉ(E) (K)"
        },
        "optional": false,
        "note": "旅游/商务短期访问选 B 类；选完后会冒 sub-question 选具体子项(代填只到这一层)",
        "whenSrc": null
      },
      {
        "label": "Have you made specific travel plans?",
        "profile": "travel.hasPlan",
        "input": "radio",
        "valueMap": {
          "true": "YES",
          "false": "NO"
        },
        "optional": false,
        "note": "已订机票酒店选 YES",
        "whenSrc": null
      },
      {
        "label": "Intended Date of Arrival",
        "profile": "travel.arrivalDate",
        "input": "date",
        "transform": "date",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Intended Length of Stay",
        "profile": "travel.stayLength",
        "input": "text",
        "transform": "upper",
        "optional": false,
        "note": "如 10 DAYS(纯数字 + DAYS,大写)",
        "whenSrc": null
      },
      {
        "label": "Address Where You Will Stay in the U.S.",
        "profile": "travel.usAddress",
        "input": "text",
        "optional": false,
        "note": "酒店名 + 地址",
        "whenSrc": null
      },
      {
        "label": "Person/Entity Paying for Your Trip",
        "profile": "travel.payer",
        "input": "select",
        "valueMap": {
          "self": "SELF",
          "other": "OTHER",
          "otherPerson": "OTHER PERSON",
          "presentEmployer": "PRESENT EMPLOYER",
          "preEmployer": "PREVIOUS EMPLOYER"
        },
        "optional": false,
        "note": "自费选 SELF",
        "whenSrc": null
      }
    ]
  },
  {
    "section": "family_spouse",
    "officialTitle": "Family — Spouse",
    "manual": false,
    "whenSrc": "function (p) { return _looseEqual(_get(p, \"identity.maritalStatus\"), \"married\") }",
    "fields": [
      {
        "label": "Spouse's Surnames",
        "profile": "family.spouse.surname",
        "input": "text",
        "transform": "upper",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Spouse's Given Names",
        "profile": "family.spouse.givenName",
        "input": "text",
        "transform": "upper",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Spouse's Date of Birth",
        "profile": "family.spouse.dob",
        "input": "date",
        "transform": "date",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Spouse's Nationality",
        "profile": "family.spouse.nationality",
        "input": "select",
        "valueMap": {
          "AF": "AFGHANISTAN",
          "AX": "ALAND ISLANDS",
          "AL": "ALBANIA",
          "DZ": "ALGERIA",
          "AS": "AMERICAN SAMOA",
          "AD": "ANDORRA",
          "AO": "ANGOLA",
          "AI": "ANGUILLA",
          "AQ": "ANTARCTICA",
          "AG": "ANTIGUA AND BARBUDA",
          "AR": "ARGENTINA",
          "AM": "ARMENIA",
          "AW": "ARUBA",
          "AU": "AUSTRALIA",
          "AT": "AUSTRIA",
          "AZ": "AZERBAIJAN",
          "BS": "BAHAMAS",
          "BH": "BAHRAIN",
          "BD": "BANGLADESH",
          "BB": "BARBADOS",
          "BY": "BELARUS",
          "BE": "BELGIUM",
          "BZ": "BELIZE",
          "BJ": "BENIN",
          "BM": "BERMUDA",
          "BT": "BHUTAN",
          "BO": "BOLIVIA",
          "BA": "BOSNIA AND HERZEGOVINA",
          "BW": "BOTSWANA",
          "BV": "BOUVET ISLAND",
          "BR": "BRAZIL",
          "IO": "BRITISH INDIAN OCEAN TERRITORY",
          "BN": "BRUNEI DARUSSALAM",
          "BG": "BULGARIA",
          "BF": "BURKINA FASO",
          "BI": "BURUNDI",
          "KH": "CAMBODIA",
          "CM": "CAMEROON",
          "CA": "CANADA",
          "CV": "CAPE VERDE",
          "KY": "CAYMAN ISLANDS",
          "CF": "CENTRAL AFRICAN REPUBLIC",
          "TD": "CHAD",
          "CL": "CHILE",
          "CN": "CHINA, PEOPLE'S REPUBLIC OF",
          "CN_MAINLAND": "CHINA-MAINLAND",
          "CN_HK": "CHINA, HONG KONG SAR",
          "CN_MACAU": "CHINA, MACAU SAR",
          "CN_TAIWAN": "CHINA, TAIWAN",
          "CX": "CHRISTMAS ISLAND",
          "CC": "COCOS ISLANDS",
          "CO": "COLOMBIA",
          "KM": "COMOROS",
          "CG": "CONGO",
          "CD": "CONGO, DEMOCRATIC REPUBLIC OF THE",
          "CK": "COOK ISLANDS",
          "CR": "COSTA RICA",
          "CI": "COTE D'IVOIRE",
          "HR": "CROATIA",
          "CU": "CUBA",
          "CY": "CYPRUS",
          "CZ": "CZECH REPUBLIC",
          "DK": "DENMARK",
          "DJ": "DJIBOUTI",
          "DM": "DOMINICA",
          "DO": "DOMINICAN REPUBLIC",
          "EC": "ECUADOR",
          "EG": "EGYPT",
          "SV": "EL SALVADOR",
          "GQ": "EQUATORIAL GUINEA",
          "ER": "ERITREA",
          "EE": "ESTONIA",
          "ET": "ETHIOPIA",
          "FK": "FALKLAND ISLANDS",
          "FO": "FAROE ISLANDS",
          "FJ": "FIJI",
          "FI": "FINLAND",
          "FR": "FRANCE",
          "GF": "FRENCH GUIANA",
          "PF": "FRENCH POLYNESIA",
          "TF": "FRENCH SOUTHERN TERRITORIES",
          "GA": "GABON",
          "GM": "GAMBIA",
          "GE": "GEORGIA",
          "DE": "GERMANY",
          "GH": "GHANA",
          "GI": "GIBRALTAR",
          "GR": "GREECE",
          "GL": "GREENLAND",
          "GD": "GRENADA",
          "GP": "GUADELOUPE",
          "GU": "GUAM",
          "GT": "GUATEMALA",
          "GG": "GUERNSEY",
          "GN": "GUINEA",
          "GW": "GUINEA-BISSAU",
          "GY": "GUYANA",
          "HT": "HAITI",
          "HM": "HEARD ISLAND AND MCDONALD ISLANDS",
          "VA": "HOLY SEE (VATICAN CITY STATE)",
          "HN": "HONDURAS",
          "HK": "HONG KONG",
          "HU": "HUNGARY",
          "IS": "ICELAND",
          "IN": "INDIA",
          "ID": "INDONESIA",
          "IR": "IRAN, ISLAMIC REPUBLIC OF",
          "IQ": "IRAQ",
          "IE": "IRELAND",
          "IM": "ISLE OF MAN",
          "IL": "ISRAEL",
          "IT": "ITALY",
          "JM": "JAMAICA",
          "JP": "JAPAN",
          "JE": "JERSEY",
          "JO": "JORDAN",
          "KZ": "KAZAKHSTAN",
          "KE": "KENYA",
          "KI": "KIRIBATI",
          "KP": "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
          "KR": "KOREA, REPUBLIC OF",
          "KW": "KUWAIT",
          "KG": "KYRGYZSTAN",
          "LA": "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
          "LV": "LATVIA",
          "LB": "LEBANON",
          "LS": "LESOTHO",
          "LR": "LIBERIA",
          "LY": "LIBYAN ARAB JAMAHIRIYA",
          "LI": "LIECHTENSTEIN",
          "LT": "LITHUANIA",
          "LU": "LUXEMBOURG",
          "MO": "MACAO",
          "MK": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
          "MG": "MADAGASCAR",
          "MW": "MALAWI",
          "MY": "MALAYSIA",
          "MV": "MALDIVES",
          "ML": "MALI",
          "MT": "MALTA",
          "MH": "MARSHALL ISLANDS",
          "MQ": "MARTINIQUE",
          "MR": "MAURITANIA",
          "MU": "MAURITIUS",
          "YT": "MAYOTTE",
          "MX": "MEXICO",
          "FM": "MICRONESIA, FEDERATED STATES OF",
          "MD": "MOLDOVA, REPUBLIC OF",
          "MC": "MONACO",
          "MN": "MONGOLIA",
          "ME": "MONTENEGRO",
          "MS": "MONTSERRAT",
          "MA": "MOROCCO",
          "MZ": "MOZAMBIQUE",
          "MM": "MYANMAR",
          "NA": "NAMIBIA",
          "NR": "NAURU",
          "NP": "NEPAL",
          "NL": "NETHERLANDS",
          "AN": "NETHERLANDS ANTILLES",
          "NC": "NEW CALEDONIA",
          "NZ": "NEW ZEALAND",
          "NI": "NICARAGUA",
          "NE": "NIGER",
          "NG": "NIGERIA",
          "NU": "NIUE",
          "NF": "NORFOLK ISLAND",
          "MK_NORTH": "NORTH MACEDONIA",
          "MP": "NORTHERN MARIANA ISLANDS",
          "NO": "NORWAY",
          "OM": "OMAN",
          "PK": "PAKISTAN",
          "PW": "PALAU",
          "PS": "PALESTINIAN TERRITORY, OCCUPIED",
          "PA": "PANAMA",
          "PG": "PAPUA NEW GUINEA",
          "PY": "PARAGUAY",
          "PE": "PERU",
          "PH": "PHILIPPINES",
          "PN": "PITCAIRN",
          "PL": "POLAND",
          "PT": "PORTUGAL",
          "PR": "PUERTO RICO",
          "QA": "QATAR",
          "RE": "REUNION",
          "RO": "ROMANIA",
          "RU": "RUSSIAN FEDERATION",
          "RW": "RWANDA",
          "SH": "SAINT HELENA",
          "KN": "SAINT KITTS AND NEVIS",
          "LC": "SAINT LUCIA",
          "PM": "SAINT PIERRE AND MIQUELON",
          "VC": "SAINT VINCENT AND THE GRENADINES",
          "WS": "SAMOA",
          "SM": "SAN MARINO",
          "ST": "SAO TOME AND PRINCIPE",
          "SA": "SAUDI ARABIA",
          "SN": "SENEGAL",
          "RS": "SERBIA",
          "SC": "SEYCHELLES",
          "SL": "SIERRA LEONE",
          "SG": "SINGAPORE",
          "SK": "SLOVAKIA",
          "SI": "SLOVENIA",
          "SB": "SOLOMON ISLANDS",
          "SO": "SOMALIA",
          "ZA": "SOUTH AFRICA",
          "GS": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
          "ES": "SPAIN",
          "LK": "SRI LANKA",
          "SD": "SUDAN",
          "SR": "SURINAME",
          "SJ": "SVALBARD AND JAN MAYEN",
          "SZ": "SWAZILAND",
          "SE": "SWEDEN",
          "CH": "SWITZERLAND",
          "SY": "SYRIAN ARAB REPUBLIC",
          "TW": "TAIWAN",
          "TJ": "TAJIKISTAN",
          "TZ": "TANZANIA, UNITED REPUBLIC OF",
          "TH": "THAILAND",
          "TL": "TIMOR-LESTE",
          "TG": "TOGO",
          "TK": "TOKELAU",
          "TO": "TONGA",
          "TT": "TRINIDAD AND TOBAGO",
          "TN": "TUNISIA",
          "TR": "TURKEY",
          "TM": "TURKMENISTAN",
          "TC": "TURKS AND CAICOS ISLANDS",
          "TV": "TUVALU",
          "UG": "UGANDA",
          "UA": "UKRAINE",
          "AE": "UNITED ARAB EMIRATES",
          "GB": "UNITED KINGDOM",
          "US": "UNITED STATES",
          "UM": "UNITED STATES MINOR OUTLYING ISLANDS",
          "UY": "URUGUAY",
          "UZ": "UZBEKISTAN",
          "VU": "VANUATU",
          "VE": "VENEZUELA",
          "VN": "VIETNAM",
          "VG": "VIRGIN ISLANDS, BRITISH",
          "VI": "VIRGIN ISLANDS, U.S.",
          "WF": "WALLIS AND FUTUNA",
          "EH": "WESTERN SAHARA",
          "YE": "YEMEN",
          "ZM": "ZAMBIA",
          "ZW": "ZIMBABWE",
          "XX": "STATELESS"
        },
        "optional": false,
        "note": "ISO-2 代码 → DS-160 官方下拉枚举",
        "whenSrc": null
      }
    ]
  },
  {
    "section": "travel_companions",
    "officialTitle": "Travel Companions",
    "manual": false,
    "whenSrc": null,
    "fields": [
      {
        "label": "Are there any other persons traveling with you?",
        "profile": "travel.hasCompanions",
        "input": "radio",
        "valueMap": {
          "true": "YES",
          "false": "NO"
        },
        "optional": false,
        "note": "勾 NO 可直接跳过同行人姓名/关系字段",
        "whenSrc": null
      },
      {
        "label": "Companion's Surnames",
        "profile": "travel.companion.surname",
        "input": "text",
        "transform": "upper",
        "optional": true,
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"travel.hasCompanions\"), true) }"
      },
      {
        "label": "Companion's Given Names",
        "profile": "travel.companion.givenName",
        "input": "text",
        "transform": "upper",
        "optional": true,
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"travel.hasCompanions\"), true) }"
      },
      {
        "label": "Companion's Relationship to You",
        "profile": "travel.companion.relation",
        "input": "select",
        "valueMap": {
          "spouse": "SPOUSE",
          "parent": "PARENT",
          "child": "CHILD",
          "sibling": "SIBLING",
          "otherRelative": "OTHER RELATIVE",
          "friend": "FRIEND",
          "businessAssociate": "BUSINESS ASSOCIATE",
          "employer": "EMPLOYER",
          "other": "OTHER"
        },
        "optional": true,
        "note": "DS-160 官方枚举: SPOUSE / PARENT / CHILD / SIBLING / OTHER RELATIVE / FRIEND / BUSINESS ASSOCIATE / EMPLOYER / OTHER",
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"travel.hasCompanions\"), true) }"
      }
    ]
  },
  {
    "section": "previous_us_travel",
    "officialTitle": "Previous U.S. Travel",
    "manual": false,
    "whenSrc": null,
    "fields": [
      {
        "label": "Have you ever been in the U.S.?",
        "profile": "previous.hasVisited",
        "input": "radio",
        "valueMap": {
          "true": "YES",
          "false": "NO"
        },
        "optional": false,
        "note": "5 年内或一生中任意一次入境都要填",
        "whenSrc": null
      },
      {
        "label": "Date of Last Visit",
        "profile": "previous.lastVisitDate",
        "input": "date",
        "transform": "date",
        "optional": true,
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"previous.hasVisited\"), true) }"
      },
      {
        "label": "Length of Stay on Last Visit (in days)",
        "profile": "previous.lastVisitStayDays",
        "input": "text",
        "optional": true,
        "note": "纯数字,例如 10",
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"previous.hasVisited\"), true) }"
      },
      {
        "label": "Have you ever been issued a U.S. Visa?",
        "profile": "previous.hasVisa",
        "input": "radio",
        "valueMap": {
          "true": "YES",
          "false": "NO"
        },
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Date of Last Visa Issuance",
        "profile": "previous.lastVisaDate",
        "input": "date",
        "transform": "date",
        "optional": true,
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"previous.hasVisa\"), true) }"
      },
      {
        "label": "Visa Number",
        "profile": "previous.lastVisaNumber",
        "input": "text",
        "transform": "upper",
        "optional": true,
        "note": "8 位红色数字,旧签证右下角",
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"previous.hasVisa\"), true) }"
      },
      {
        "label": "Have you ever been refused a U.S. Visa or refused admission to the U.S.?",
        "profile": "previous.hasRefused",
        "input": "radio",
        "valueMap": {
          "true": "YES",
          "false": "NO"
        },
        "optional": true,
        "note": "如实填写,后续解释说明在 Security/Background",
        "whenSrc": null
      }
    ]
  },
  {
    "section": "us_contact",
    "officialTitle": "U.S. Point of Contact",
    "manual": false,
    "whenSrc": null,
    "fields": [
      {
        "label": "Contact Person Surnames",
        "profile": "usContact.personSurname",
        "input": "text",
        "transform": "upper",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Contact Person Given Names",
        "profile": "usContact.personGivenName",
        "input": "text",
        "transform": "upper",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "Organization Name",
        "profile": "usContact.orgName",
        "input": "text",
        "optional": true,
        "note": "如酒店名称 / 邀请公司 / 学校",
        "whenSrc": null
      },
      {
        "label": "Relationship to You",
        "profile": "usContact.relation",
        "input": "select",
        "valueMap": {
          "spouse": "SPOUSE",
          "parent": "PARENT",
          "child": "CHILD",
          "sibling": "SIBLING",
          "otherRelative": "OTHER RELATIVE",
          "friend": "FRIEND",
          "businessAssociate": "BUSINESS ASSOCIATE",
          "employer": "EMPLOYER",
          "hotel": "HOTEL",
          "other": "OTHER"
        },
        "optional": true,
        "note": "DS-160 官方枚举: 同 Companion 的 Relationship, 多 HOTEL (美国联系人是酒店时)",
        "whenSrc": null
      },
      {
        "label": "U.S. Address — Street Address",
        "profile": "usContact.street",
        "input": "text",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "U.S. Address — City",
        "profile": "usContact.city",
        "input": "text",
        "optional": false,
        "whenSrc": null
      },
      {
        "label": "U.S. Address — State",
        "profile": "usContact.state",
        "input": "text",
        "optional": true,
        "note": "华盛顿特区 / 州代码两字母",
        "whenSrc": null
      },
      {
        "label": "U.S. Address — ZIP Code",
        "profile": "usContact.zip",
        "input": "text",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "U.S. Phone Number",
        "profile": "usContact.phone",
        "input": "text",
        "optional": false,
        "note": "带国家码 +1",
        "whenSrc": null
      },
      {
        "label": "Email Address",
        "profile": "usContact.email",
        "input": "text",
        "optional": true,
        "whenSrc": null
      }
    ]
  },
  {
    "section": "family_parents_children",
    "officialTitle": "Family — Parents & Children",
    "manual": false,
    "whenSrc": null,
    "fields": [
      {
        "label": "Father's Surnames",
        "profile": "family.father.surname",
        "input": "text",
        "transform": "upper",
        "optional": true,
        "note": "不知道填 \"Does Not Apply\"",
        "whenSrc": null
      },
      {
        "label": "Father's Given Names",
        "profile": "family.father.givenName",
        "input": "text",
        "transform": "upper",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Father's Date of Birth",
        "profile": "family.father.dob",
        "input": "date",
        "transform": "date",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Is your father in the U.S.?",
        "profile": "family.father.inUS",
        "input": "radio",
        "valueMap": {
          "true": "YES",
          "false": "NO"
        },
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Mother's Surnames",
        "profile": "family.mother.surname",
        "input": "text",
        "transform": "upper",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Mother's Given Names",
        "profile": "family.mother.givenName",
        "input": "text",
        "transform": "upper",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Mother's Date of Birth",
        "profile": "family.mother.dob",
        "input": "date",
        "transform": "date",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Is your mother in the U.S.?",
        "profile": "family.mother.inUS",
        "input": "radio",
        "valueMap": {
          "true": "YES",
          "false": "NO"
        },
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Do you have any immediate relatives (other than spouse) in the U.S.?",
        "profile": "family.hasUSRelatives",
        "input": "radio",
        "valueMap": {
          "true": "YES",
          "false": "NO"
        },
        "optional": true,
        "note": "父母/子女/兄弟姐妹 等直系亲属",
        "whenSrc": null
      },
      {
        "label": "Relative's Surnames",
        "profile": "family.relative.surname",
        "input": "text",
        "transform": "upper",
        "optional": true,
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"family.hasUSRelatives\"), true) }"
      },
      {
        "label": "Relative's Given Names",
        "profile": "family.relative.givenName",
        "input": "text",
        "transform": "upper",
        "optional": true,
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"family.hasUSRelatives\"), true) }"
      },
      {
        "label": "Relative's Relationship to You",
        "profile": "family.relative.relation",
        "input": "select",
        "valueMap": {
          "spouse": "SPOUSE",
          "parent": "PARENT",
          "child": "CHILD",
          "sibling": "SIBLING",
          "otherRelative": "OTHER RELATIVE"
        },
        "optional": true,
        "note": "DS-160 官方枚举: 直系亲属 (父母/配偶/子女/兄弟姐妹) + OTHER RELATIVE",
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"family.hasUSRelatives\"), true) }"
      },
      {
        "label": "Relative's Status (e.g., U.S. Citizen, LPR)",
        "profile": "family.relative.status",
        "input": "select",
        "valueMap": {
          "usCitizen": "U.S. CITIZEN",
          "lpr": "U.S. LEGAL PERMANENT RESIDENT (LPR)",
          "nonImmigrant": "U.S. NON-IMMIGRANT",
          "other": "OTHER"
        },
        "optional": true,
        "note": "DS-160 官方枚举: U.S. CITIZEN / U.S. LEGAL PERMANENT RESIDENT (LPR) / U.S. NON-IMMIGRANT / OTHER",
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"family.hasUSRelatives\"), true) }"
      }
    ]
  },
  {
    "section": "work_education",
    "officialTitle": "Work / Education / Training",
    "manual": false,
    "whenSrc": null,
    "fields": [
      {
        "label": "Primary Occupation",
        "profile": "work.occupation",
        "input": "text",
        "optional": false,
        "note": "学生/教师/工程师/医生/无业 等",
        "whenSrc": null
      },
      {
        "label": "Present Employer or School Name",
        "profile": "work.employer",
        "input": "text",
        "optional": true,
        "note": "无业/退休 填 \"Does Not Apply\"",
        "whenSrc": null
      },
      {
        "label": "Employer Address — Street",
        "profile": "work.employerStreet",
        "input": "text",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Employer Address — City",
        "profile": "work.employerCity",
        "input": "text",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Employer Address — State/Province",
        "profile": "work.employerState",
        "input": "text",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Employer Address — Postal Zone",
        "profile": "work.employerPostal",
        "input": "text",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Employer Address — Country/Region",
        "profile": "work.employerCountry",
        "input": "select",
        "valueMap": {
          "AF": "AFGHANISTAN",
          "AX": "ALAND ISLANDS",
          "AL": "ALBANIA",
          "DZ": "ALGERIA",
          "AS": "AMERICAN SAMOA",
          "AD": "ANDORRA",
          "AO": "ANGOLA",
          "AI": "ANGUILLA",
          "AQ": "ANTARCTICA",
          "AG": "ANTIGUA AND BARBUDA",
          "AR": "ARGENTINA",
          "AM": "ARMENIA",
          "AW": "ARUBA",
          "AU": "AUSTRALIA",
          "AT": "AUSTRIA",
          "AZ": "AZERBAIJAN",
          "BS": "BAHAMAS",
          "BH": "BAHRAIN",
          "BD": "BANGLADESH",
          "BB": "BARBADOS",
          "BY": "BELARUS",
          "BE": "BELGIUM",
          "BZ": "BELIZE",
          "BJ": "BENIN",
          "BM": "BERMUDA",
          "BT": "BHUTAN",
          "BO": "BOLIVIA",
          "BA": "BOSNIA AND HERZEGOVINA",
          "BW": "BOTSWANA",
          "BV": "BOUVET ISLAND",
          "BR": "BRAZIL",
          "IO": "BRITISH INDIAN OCEAN TERRITORY",
          "BN": "BRUNEI DARUSSALAM",
          "BG": "BULGARIA",
          "BF": "BURKINA FASO",
          "BI": "BURUNDI",
          "KH": "CAMBODIA",
          "CM": "CAMEROON",
          "CA": "CANADA",
          "CV": "CAPE VERDE",
          "KY": "CAYMAN ISLANDS",
          "CF": "CENTRAL AFRICAN REPUBLIC",
          "TD": "CHAD",
          "CL": "CHILE",
          "CN": "CHINA, PEOPLE'S REPUBLIC OF",
          "CN_MAINLAND": "CHINA-MAINLAND",
          "CN_HK": "CHINA, HONG KONG SAR",
          "CN_MACAU": "CHINA, MACAU SAR",
          "CN_TAIWAN": "CHINA, TAIWAN",
          "CX": "CHRISTMAS ISLAND",
          "CC": "COCOS ISLANDS",
          "CO": "COLOMBIA",
          "KM": "COMOROS",
          "CG": "CONGO",
          "CD": "CONGO, DEMOCRATIC REPUBLIC OF THE",
          "CK": "COOK ISLANDS",
          "CR": "COSTA RICA",
          "CI": "COTE D'IVOIRE",
          "HR": "CROATIA",
          "CU": "CUBA",
          "CY": "CYPRUS",
          "CZ": "CZECH REPUBLIC",
          "DK": "DENMARK",
          "DJ": "DJIBOUTI",
          "DM": "DOMINICA",
          "DO": "DOMINICAN REPUBLIC",
          "EC": "ECUADOR",
          "EG": "EGYPT",
          "SV": "EL SALVADOR",
          "GQ": "EQUATORIAL GUINEA",
          "ER": "ERITREA",
          "EE": "ESTONIA",
          "ET": "ETHIOPIA",
          "FK": "FALKLAND ISLANDS",
          "FO": "FAROE ISLANDS",
          "FJ": "FIJI",
          "FI": "FINLAND",
          "FR": "FRANCE",
          "GF": "FRENCH GUIANA",
          "PF": "FRENCH POLYNESIA",
          "TF": "FRENCH SOUTHERN TERRITORIES",
          "GA": "GABON",
          "GM": "GAMBIA",
          "GE": "GEORGIA",
          "DE": "GERMANY",
          "GH": "GHANA",
          "GI": "GIBRALTAR",
          "GR": "GREECE",
          "GL": "GREENLAND",
          "GD": "GRENADA",
          "GP": "GUADELOUPE",
          "GU": "GUAM",
          "GT": "GUATEMALA",
          "GG": "GUERNSEY",
          "GN": "GUINEA",
          "GW": "GUINEA-BISSAU",
          "GY": "GUYANA",
          "HT": "HAITI",
          "HM": "HEARD ISLAND AND MCDONALD ISLANDS",
          "VA": "HOLY SEE (VATICAN CITY STATE)",
          "HN": "HONDURAS",
          "HK": "HONG KONG",
          "HU": "HUNGARY",
          "IS": "ICELAND",
          "IN": "INDIA",
          "ID": "INDONESIA",
          "IR": "IRAN, ISLAMIC REPUBLIC OF",
          "IQ": "IRAQ",
          "IE": "IRELAND",
          "IM": "ISLE OF MAN",
          "IL": "ISRAEL",
          "IT": "ITALY",
          "JM": "JAMAICA",
          "JP": "JAPAN",
          "JE": "JERSEY",
          "JO": "JORDAN",
          "KZ": "KAZAKHSTAN",
          "KE": "KENYA",
          "KI": "KIRIBATI",
          "KP": "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
          "KR": "KOREA, REPUBLIC OF",
          "KW": "KUWAIT",
          "KG": "KYRGYZSTAN",
          "LA": "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
          "LV": "LATVIA",
          "LB": "LEBANON",
          "LS": "LESOTHO",
          "LR": "LIBERIA",
          "LY": "LIBYAN ARAB JAMAHIRIYA",
          "LI": "LIECHTENSTEIN",
          "LT": "LITHUANIA",
          "LU": "LUXEMBOURG",
          "MO": "MACAO",
          "MK": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
          "MG": "MADAGASCAR",
          "MW": "MALAWI",
          "MY": "MALAYSIA",
          "MV": "MALDIVES",
          "ML": "MALI",
          "MT": "MALTA",
          "MH": "MARSHALL ISLANDS",
          "MQ": "MARTINIQUE",
          "MR": "MAURITANIA",
          "MU": "MAURITIUS",
          "YT": "MAYOTTE",
          "MX": "MEXICO",
          "FM": "MICRONESIA, FEDERATED STATES OF",
          "MD": "MOLDOVA, REPUBLIC OF",
          "MC": "MONACO",
          "MN": "MONGOLIA",
          "ME": "MONTENEGRO",
          "MS": "MONTSERRAT",
          "MA": "MOROCCO",
          "MZ": "MOZAMBIQUE",
          "MM": "MYANMAR",
          "NA": "NAMIBIA",
          "NR": "NAURU",
          "NP": "NEPAL",
          "NL": "NETHERLANDS",
          "AN": "NETHERLANDS ANTILLES",
          "NC": "NEW CALEDONIA",
          "NZ": "NEW ZEALAND",
          "NI": "NICARAGUA",
          "NE": "NIGER",
          "NG": "NIGERIA",
          "NU": "NIUE",
          "NF": "NORFOLK ISLAND",
          "MK_NORTH": "NORTH MACEDONIA",
          "MP": "NORTHERN MARIANA ISLANDS",
          "NO": "NORWAY",
          "OM": "OMAN",
          "PK": "PAKISTAN",
          "PW": "PALAU",
          "PS": "PALESTINIAN TERRITORY, OCCUPIED",
          "PA": "PANAMA",
          "PG": "PAPUA NEW GUINEA",
          "PY": "PARAGUAY",
          "PE": "PERU",
          "PH": "PHILIPPINES",
          "PN": "PITCAIRN",
          "PL": "POLAND",
          "PT": "PORTUGAL",
          "PR": "PUERTO RICO",
          "QA": "QATAR",
          "RE": "REUNION",
          "RO": "ROMANIA",
          "RU": "RUSSIAN FEDERATION",
          "RW": "RWANDA",
          "SH": "SAINT HELENA",
          "KN": "SAINT KITTS AND NEVIS",
          "LC": "SAINT LUCIA",
          "PM": "SAINT PIERRE AND MIQUELON",
          "VC": "SAINT VINCENT AND THE GRENADINES",
          "WS": "SAMOA",
          "SM": "SAN MARINO",
          "ST": "SAO TOME AND PRINCIPE",
          "SA": "SAUDI ARABIA",
          "SN": "SENEGAL",
          "RS": "SERBIA",
          "SC": "SEYCHELLES",
          "SL": "SIERRA LEONE",
          "SG": "SINGAPORE",
          "SK": "SLOVAKIA",
          "SI": "SLOVENIA",
          "SB": "SOLOMON ISLANDS",
          "SO": "SOMALIA",
          "ZA": "SOUTH AFRICA",
          "GS": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
          "ES": "SPAIN",
          "LK": "SRI LANKA",
          "SD": "SUDAN",
          "SR": "SURINAME",
          "SJ": "SVALBARD AND JAN MAYEN",
          "SZ": "SWAZILAND",
          "SE": "SWEDEN",
          "CH": "SWITZERLAND",
          "SY": "SYRIAN ARAB REPUBLIC",
          "TW": "TAIWAN",
          "TJ": "TAJIKISTAN",
          "TZ": "TANZANIA, UNITED REPUBLIC OF",
          "TH": "THAILAND",
          "TL": "TIMOR-LESTE",
          "TG": "TOGO",
          "TK": "TOKELAU",
          "TO": "TONGA",
          "TT": "TRINIDAD AND TOBAGO",
          "TN": "TUNISIA",
          "TR": "TURKEY",
          "TM": "TURKMENISTAN",
          "TC": "TURKS AND CAICOS ISLANDS",
          "TV": "TUVALU",
          "UG": "UGANDA",
          "UA": "UKRAINE",
          "AE": "UNITED ARAB EMIRATES",
          "GB": "UNITED KINGDOM",
          "US": "UNITED STATES",
          "UM": "UNITED STATES MINOR OUTLYING ISLANDS",
          "UY": "URUGUAY",
          "UZ": "UZBEKISTAN",
          "VU": "VANUATU",
          "VE": "VENEZUELA",
          "VN": "VIETNAM",
          "VG": "VIRGIN ISLANDS, BRITISH",
          "VI": "VIRGIN ISLANDS, U.S.",
          "WF": "WALLIS AND FUTUNA",
          "EH": "WESTERN SAHARA",
          "YE": "YEMEN",
          "ZM": "ZAMBIA",
          "ZW": "ZIMBABWE",
          "XX": "STATELESS"
        },
        "optional": true,
        "note": "ISO-2 代码 → DS-160 官方下拉枚举",
        "whenSrc": null
      },
      {
        "label": "Employer Phone Number",
        "profile": "work.employerPhone",
        "input": "text",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Monthly Salary in Local Currency (if employed)",
        "profile": "work.monthlySalary",
        "input": "text",
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Briefly describe your duties",
        "profile": "work.duties",
        "input": "textarea",
        "optional": true,
        "note": "一两句中文/英文都可",
        "whenSrc": null
      },
      {
        "label": "Have you attended any educational institutions at a secondary level or above?",
        "profile": "work.hasEducation",
        "input": "radio",
        "valueMap": {
          "true": "YES",
          "false": "NO"
        },
        "optional": true,
        "whenSrc": null
      },
      {
        "label": "Name of Institution",
        "profile": "work.schoolName",
        "input": "text",
        "optional": true,
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"work.hasEducation\"), true) }"
      },
      {
        "label": "Course of Study",
        "profile": "work.courseOfStudy",
        "input": "text",
        "optional": true,
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"work.hasEducation\"), true) }"
      },
      {
        "label": "Date of Attendance — From",
        "profile": "work.schoolFrom",
        "input": "date",
        "transform": "date",
        "optional": true,
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"work.hasEducation\"), true) }"
      },
      {
        "label": "Date of Attendance — To",
        "profile": "work.schoolTo",
        "input": "date",
        "transform": "date",
        "optional": true,
        "whenSrc": "function (p) { return _looseEqual(_get(p, \"work.hasEducation\"), true) }"
      },
      {
        "label": "Name of Previous Employer (if applicable)",
        "profile": "work.prevEmployer",
        "input": "text",
        "optional": true,
        "whenSrc": null
      }
    ]
  },
  {
    "section": "security_background",
    "officialTitle": "Security and Background",
    "manual": true,
    "note": "此 section 涉及法律/健康/犯罪/移民历史等问题,必须由申请人本人在 ceac.state.gov 上如实回答。Htex 仅做\"已读/确认\"标记,不做代填。",
    "whenSrc": null,
    "fields": [
      {
        "label": "Security & Background — 已阅读并理解所有 5 大类问题",
        "profile": "security.acknowledged",
        "input": "radio",
        "valueMap": {
          "true": "YES",
          "false": "NO"
        },
        "optional": false,
        "note": "Part 1: Disease / Health / Addictive; Part 2: Criminal / Security; Part 3: Immigration / Visa fraud; Part 4: Public benefit / Removable; Part 5: Misc. 详见 DS-160 官方源。",
        "whenSrc": null
      }
    ]
  }
]

  // ---- 日期归一 ----
  function _toDs160Date(raw) {
    var m = String(raw).trim().match(/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$/)
    if (!m) return String(raw)
    var mon = MONTHS[+m[2] - 1]
    if (!mon) return String(raw)
    return String(+m[3]).padStart(2, '0') + '-' + mon + '-' + m[1]
  }
  function _getField(o, p) { return _get(o, p) }
  function _isEmpty(v) { return !_isNonEmpty(v) }

  function _isEmpty(v) { return !_isNonEmpty(v) }

  function _coerceBoolForValueMap(raw) {
    if (raw === true || raw === false) return raw
    var s = String(raw).trim().toLowerCase()
    if (s === 'true' || s === 'yes' || s === 'y' || s === '1') return true
    if (s === 'false' || s === 'no' || s === 'n' || s === '0') return false
    return raw
  }

  function _resolveValueMap(raw, valueMap) {
    if (!valueMap || _isEmpty(raw)) return raw
    if (valueMap[raw] !== undefined) return valueMap[raw]
    if (valueMap[String(raw)] !== undefined) return valueMap[String(raw)]
    var coerced = _coerceBoolForValueMap(raw)
    if (coerced !== raw && valueMap[coerced] !== undefined) return valueMap[coerced]
    var up = String(raw).trim().toUpperCase()
    var vals = Object.keys(valueMap).map(function (k) { return valueMap[k] })
    for (var i = 0; i < vals.length; i++) {
      if (String(vals[i]).toUpperCase() === up) return vals[i]
    }
    for (var j = 0; j < vals.length; j++) {
      var vu = String(vals[j]).toUpperCase()
      if (vu.indexOf(up) !== -1 || up.indexOf(vu) !== -1) return vals[j]
    }
    return raw
  }

  function _isPortalEnumResolved(raw, valueMap) {
    if (!valueMap || _isEmpty(raw)) return true
    if (valueMap[raw] !== undefined) return true
    if (valueMap[String(raw)] !== undefined) return true
    var coerced = _coerceBoolForValueMap(raw)
    if (coerced !== raw && valueMap[coerced] !== undefined) return true
    var up = String(raw).trim().toUpperCase()
    var vals = Object.keys(valueMap).map(function (k) { return valueMap[k] })
    for (var i = 0; i < vals.length; i++) {
      if (String(vals[i]).toUpperCase() === up) return true
    }
    for (var j = 0; j < vals.length; j++) {
      var vu = String(vals[j]).toUpperCase()
      if (vu.indexOf(up) !== -1 || up.indexOf(vu) !== -1) return true
    }
    return false
  }

  // ---- 字段解析 ----
  function resolveField(field, profile) {
    var raw = _getField(profile, field.profile)
    if (_isEmpty(raw)) {
      if (field.optional) return { label: field.label, profile: field.profile, input: field.input, action: 'na', value: 'Does Not Apply', missing: false, optional: true, note: field.note }
      return { label: field.label, profile: field.profile, input: field.input, action: 'todo', value: null, missing: true, optional: false, note: field.note }
    }
    var value = _resolveValueMap(raw, field.valueMap)
    if (field.valueMap && (field.input === 'select' || field.input === 'radio') && !_isPortalEnumResolved(raw, field.valueMap)) {
      return { label: field.label, profile: field.profile, input: field.input, action: 'todo', value: null, missing: true, optional: false, note: field.note }
    }
    if (field.transform === 'upper') value = String(value).toUpperCase()
    else if (field.transform === 'date') value = _toDs160Date(value)
    return { label: field.label, profile: field.profile, input: field.input, action: 'fill', value: value, missing: false, optional: !!field.optional, note: field.note }
  }

  // ---- 编译 when 函数字符串 → 真函数 ----
  // src 形如 "function (p) { return _looseEqual(...) }"
  // 提取函数体含 return,包进 new Function 即可
  function _compileWhenSrc(src) {
    var open = src.indexOf('{')
    var close = src.lastIndexOf('}')
    var body = src.substring(open + 1, close)
    return new Function('p', '_get', '_isNonEmpty', '_looseEqual', '_boolCoerce', body)
  }

  // ---- 引导单生成 ----
  function buildGuide(profile) {
    profile = profile || {}
    var missingCount = 0
    var sections = MAP
      .map(function (sec) {
        // 把 whenSrc 编译成真函数
        var secWhen = sec.whenSrc ? _compileWhenSrc(sec.whenSrc) : null
        var secPass = !sec.manual && (!secWhen || secWhen(profile, _get, _isNonEmpty, _looseEqual, _boolCoerce))
        if (!secPass) return null
        var steps = sec.fields
          .filter(function (f) {
            if (!f.whenSrc) return true
            var fn = _compileWhenSrc(f.whenSrc)
            return fn(profile, _get, _isNonEmpty, _looseEqual, _boolCoerce)
          })
          .map(function (f) {
            var s = resolveField(f, profile)
            if (s.missing) missingCount++
            return s
          })
        return { section: sec.section, officialTitle: sec.officialTitle, manual: sec.manual, steps: steps }
      })
      .filter(function (s) { return s !== null })
    return {
      meta: { version: VERSION, verifiedDate: VERIFIED_DATE },
      sections: sections,
      manualSteps: ["Getting Started 页:选申请地点、创建 Application ID、设置安全问题(请自己记牢)","U.S. Point of Contact 页:填美国联系人/单位(如酒店或邀请方)","Work/Education 页:填职业、雇主/学校信息","Security and Background 页:一系列 Yes/No 背景问题(必须本人如实回答)","上传符合规格的照片","核对全部内容 → 电子签名 → 提交"],
      missingCount: missingCount,
    }
  }

  window.HTEX = window.HTEX || {}
  window.HTEX.MAP = MAP
  window.HTEX.buildGuide = buildGuide
})()
